// <auto-generated />
namespace Postermania.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Adddescriptiontoposter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Adddescriptiontoposter));
        
        string IMigrationMetadata.Id
        {
            get { return "202208290005386_Add description to poster"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
